name: macOS CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        build_shared_libs: [BUILD_SHARED_LIBS=True, BUILD_SHARED_LIBS=False]

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule sync --recursive && git submodule update --init --recursive
    - name: Install dependencies
      run: brew install cmake ninja boost
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -D${{ matrix.build_shared_libs }}
    - name: Build
      run: |
        cd build
        cmake --build .
    - name: Test
      run: |
        cd build
        ctest --output-on-failure
